---

  - name: Install iptables-services
    yum: name=iptables-services state=installed
    tags: rpm

  - name: Disable firewalld
    service: name=firewalld state=stopped enabled=no
    ignore_errors: yes # The firewalld service might not be installed, ignore error

  - name: Enable iptables
    service: name=iptables state=started enabled=yes
