---

  - name: Install iptables-services
    yum: name=iptables-services state=installed
    tags: rpm

  - name: Disable firewalld
    service: name=firewalld state=stopped enabled=no
    ignore_errors: yes # The firewalld service might not be installed, ignore error

  - name: Enable iptables
    service: name=iptables state=started enabled=yes

  - name: First, disable any repos (using subscription-manager)
    command: subscription-manager repos --disable="*"
    when: 'not is_offline|default(False)|bool'
    tags: rpm

  - name: Make sure mandatory repos are enabled
    command: subscription-manager repos --enable {{ item }}
    with_items:
      - rhel-7-server-rpms
      - rhel-7-server-optional-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-{{ lab_openshift_version }}-rpms
      - rhel-7-fast-datapath-rpms # see https://access.redhat.com/solutions/3008401
    when: 'not is_offline|default(False)'
    tags: rpm

  - name: Install nfs-utils
    yum: name=nfs-utils state=installed
    tags: rpm

  - name: Install bash-completion
    yum: name=bash-completion state=installed
    when: "'masters' in group_names" # Only on master server
    tags: rpm

  - name: Install NetworkManager
    yum: name=NetworkManager state=installed
    tags: rpm

  - name: Install net-tools
    yum: name=net-tools state=installed
    tags: rpm

  - name: Install bind-utils
    yum: name=bind-utils state=installed
    tags: rpm

  - name: Install httpd-tools
    yum: name=httpd-tools state=installed
    tags: rpm
