---

  threescale_template: https://raw.githubusercontent.com/nmasse-itix/OpenShift-Lab/master/roles/3scale/files/amp.json
  threescale_project: 3scale
  threescale_tenant_name: 3scale
  threescale_wildcard_domain: "{{ openshift_master_default_subdomain }}"
  threescale_delay: 5
  threescale_retries: 30
  threescale_apicast_cors_lua: https://raw.githubusercontent.com/3scale/apicast/cors-example/examples/cors/apicast_cors.lua
  threescale_apicast_cors_conf: https://raw.githubusercontent.com/3scale/apicast/cors-example/examples/cors/cors.conf
