---

  - name: Get the 3scale Administration Access Token
    command: oc get dc system-app -n "{{ threescale_project }}" -o 'jsonpath={.spec.template.spec.containers[0].env[?(@.name=="ADMIN_ACCESS_TOKEN")].value}'
    register: oc_get_dc
    tags: vars
    changed_when: false

  - set_fact:
      access_token: '{{ oc_get_dc.stdout }}'
    tags: vars

  - include: 3scale_status.yml
    
  - include: create_api.yml
    with_items: '{{ threescale_apis_to_create }}'
